// Service Configuration
export const SERVICES = [
  {
    id: 1,
    name: 'Marriage Biodata Maker',
    slug: 'marriage-biodata-maker',
    description: 'Create beautiful marriage biodata with traditional and modern formats',
    icon: '💑',
    templateCount: 10,
    category: 'marriage' as const,
  },
  {
    id: 2,
    name: 'Wedding Invitation Cards',
    slug: 'wedding-invitation-cards',
    description: 'Design stunning wedding invitation cards',
    icon: '💒',
    templateCount: 10,
    category: 'marriage' as const,
  },
  {
    id: 3,
    name: 'Pre-Wedding Templates',
    slug: 'pre-wedding-templates',
    description: 'Save the date and engagement invitations',
    icon: '💍',
    templateCount: 10,
    category: 'marriage' as const,
  },
  {
    id: 4,
    name: 'Biodata Posters',
    slug: 'biodata-posters',
    description: 'Social media ready biodata posters',
    icon: '📱',
    templateCount: 10,
    category: 'marriage' as const,
  },
  {
    id: 5,
    name: 'Resume/CV Maker',
    slug: 'resume-cv-maker',
    description: 'Professional ATS-friendly resume templates',
    icon: '📄',
    templateCount: 10,
    category: 'career' as const,
  },
  {
    id: 6,
    name: 'Cover Letter Templates',
    slug: 'cover-letter-templates',
    description: 'Compelling cover letters',
    icon: '✉️',
    templateCount: 10,
    category: 'career' as const,
  },
  {
    id: 7,
    name: 'Portfolio Websites',
    slug: 'portfolio-websites',
    description: 'Professional portfolio templates',
    icon: '💼',
    templateCount: 10,
    category: 'career' as const,
  },
  {
    id: 8,
    name: 'LinkedIn Banner Designs',
    slug: 'linkedin-banner-designs',
    description: 'Professional LinkedIn banners',
    icon: '🌐',
    templateCount: 10,
    category: 'career' as const,
  },
  {
    id: 9,
    name: 'ID Card Maker',
    slug: 'id-card-maker',
    description: 'Employee and student ID cards',
    icon: '🎫',
    templateCount: 10,
    category: 'business' as const,
  },
  {
    id: 10,
    name: 'Certificate Generator',
    slug: 'certificate-generator',
    description: 'Professional certificates',
    icon: '🏆',
    templateCount: 10,
    category: 'business' as const,
  },
  {
    id: 11,
    name: 'Business Card Designer',
    slug: 'business-card-designer',
    description: 'Custom business cards',
    icon: '💳',
    templateCount: 10,
    category: 'business' as const,
  },
  {
    id: 12,
    name: 'Letterhead Templates',
    slug: 'letterhead-templates',
    description: 'Professional letterheads',
    icon: '📝',
    templateCount: 10,
    category: 'business' as const,
  },
];

// SEO Keywords
export const SEO_KEYWORDS = {
  homepage: [
    'marriage biodata maker',
    'resume builder',
    'wedding invitation',
    'biodata format',
    'free CV maker',
    'online document creator',
    'Indian biodata template',
    'shaadi biodata',
    'job resume',
  ],
  marriageBiodata: [
    'marriage biodata format',
    'biodata for marriage',
    'shaadi biodata',
    'Hindu biodata template',
    'Muslim biodata',
    'matrimonial biodata',
    'bride biodata',
    'groom biodata',
  ],
  resume: [
    'resume builder India',
    'fresher resume format',
    'ATS resume template',
    'professional CV maker',
    'job resume',
    'free resume creator',
    'resume for freshers',
  ],
};

// Site Configuration
export const SITE_CONFIG = {
  name: 'BioDatawala',
  url: 'https://biodatawala.in',
  description: 'Professional SEO-optimized multi-service document design platform',
  email: 'support@biodatawala.in',
  socialMedia: {
    facebook: 'https://facebook.com/biodatawala',
    instagram: 'https://instagram.com/biodatawala',
    twitter: 'https://twitter.com/biodatawala',
    linkedin: 'https://linkedin.com/company/biodatawala',
  },
};
