import { Template } from '@/types';

// Marriage Biodata Templates
export const marriageBiodataTemplates: Template[] = [
  {
    id: 'mb-001',
    name: 'Traditional Hindu Biodata',
    description: 'Classic border design with Ganesh symbol, maroon and gold colors',
    serviceId: 1,
    category: 'marriage',
    style: 'traditional',
    thumbnail: '/templates/marriage-biodata/hindu-traditional.jpg',
    previewUrl: '/template/mb-001/preview',
    isPremium: false,
    tags: ['Hindu', 'Traditional', 'Ornate'],
  },
  {
    id: 'mb-002',
    name: 'Modern Minimalist Biodata',
    description: 'Clean layout with pastel colors and contemporary fonts',
    serviceId: 1,
    category: 'marriage',
    style: 'minimalist',
    thumbnail: '/templates/marriage-biodata/modern-minimalist.jpg',
    previewUrl: '/template/mb-002/preview',
    isPremium: false,
    tags: ['Modern', 'Minimalist', 'Clean'],
  },
  {
    id: 'mb-003',
    name: 'Muslim Nikah Biodata',
    description: 'Islamic patterns with crescent motifs and elegant typography',
    serviceId: 1,
    category: 'marriage',
    style: 'elegant',
    thumbnail: '/templates/marriage-biodata/muslim-nikah.jpg',
    previewUrl: '/template/mb-003/preview',
    isPremium: false,
    tags: ['Muslim', 'Islamic', 'Elegant'],
  },
  {
    id: 'mb-004',
    name: 'Christian Marriage Resume',
    description: 'Simple elegant design with cross symbol, white and gold theme',
    serviceId: 1,
    category: 'marriage',
    style: 'classic',
    thumbnail: '/templates/marriage-biodata/christian-classic.jpg',
    previewUrl: '/template/mb-004/preview',
    isPremium: false,
    tags: ['Christian', 'Classic', 'Simple'],
  },
  {
    id: 'mb-005',
    name: 'South Indian Biodata',
    description: 'Temple-inspired borders with traditional colors and regional details',
    serviceId: 1,
    category: 'marriage',
    style: 'traditional',
    thumbnail: '/templates/marriage-biodata/south-indian.jpg',
    previewUrl: '/template/mb-005/preview',
    isPremium: true,
    tags: ['South Indian', 'Traditional', 'Cultural'],
  },
  {
    id: 'mb-006',
    name: 'Marwari Biodata',
    description: 'Ornate Rajasthani patterns with rich colors and detailed format',
    serviceId: 1,
    category: 'marriage',
    style: 'premium',
    thumbnail: '/templates/marriage-biodata/marwari.jpg',
    previewUrl: '/template/mb-006/preview',
    isPremium: true,
    tags: ['Marwari', 'Rajasthani', 'Ornate'],
  },
  {
    id: 'mb-007',
    name: 'Professional Photo Biodata',
    description: 'Large photo section with clean professional layout',
    serviceId: 1,
    category: 'marriage',
    style: 'professional',
    thumbnail: '/templates/marriage-biodata/photo-professional.jpg',
    previewUrl: '/template/mb-007/preview',
    isPremium: false,
    tags: ['Photo-focused', 'Professional', 'Modern'],
  },
  {
    id: 'mb-008',
    name: 'Floral Design Biodata',
    description: 'Flower borders with soft romantic colors and decorative elements',
    serviceId: 1,
    category: 'marriage',
    style: 'elegant',
    thumbnail: '/templates/marriage-biodata/floral.jpg',
    previewUrl: '/template/mb-008/preview',
    isPremium: true,
    tags: ['Floral', 'Romantic', 'Elegant'],
  },
  {
    id: 'mb-009',
    name: 'Royal Palace Biodata',
    description: 'Luxurious design with gold accents and premium feel',
    serviceId: 1,
    category: 'marriage',
    style: 'premium',
    thumbnail: '/templates/marriage-biodata/royal-palace.jpg',
    previewUrl: '/template/mb-009/preview',
    isPremium: true,
    tags: ['Luxury', 'Royal', 'Premium'],
  },
  {
    id: 'mb-010',
    name: 'Simple One-Page Biodata',
    description: 'Minimalist design with all essential info, printer-friendly',
    serviceId: 1,
    category: 'marriage',
    style: 'minimalist',
    thumbnail: '/templates/marriage-biodata/simple-one-page.jpg',
    previewUrl: '/template/mb-010/preview',
    isPremium: false,
    tags: ['Simple', 'One-page', 'Practical'],
  },
];

// Resume Templates
export const resumeTemplates: Template[] = [
  {
    id: 'res-001',
    name: 'ATS-Friendly Resume',
    description: 'Plain text format optimized for Applicant Tracking Systems',
    serviceId: 6,
    category: 'career',
    style: 'professional',
    thumbnail: '/templates/resume/ats-friendly.jpg',
    previewUrl: '/template/res-001/preview',
    isPremium: false,
    tags: ['ATS', 'Professional', 'Clean'],
  },
  {
    id: 'res-002',
    name: 'Modern Professional CV',
    description: 'Clean sections with blue accents and contemporary layout',
    serviceId: 6,
    category: 'career',
    style: 'modern',
    thumbnail: '/templates/resume/modern-professional.jpg',
    previewUrl: '/template/res-002/preview',
    isPremium: false,
    tags: ['Modern', 'Professional', 'Blue'],
  },
  {
    id: 'res-003',
    name: 'Creative Designer Resume',
    description: 'Colorful design with graphic elements for creative professionals',
    serviceId: 6,
    category: 'career',
    style: 'creative',
    thumbnail: '/templates/resume/creative-designer.jpg',
    previewUrl: '/template/res-003/preview',
    isPremium: true,
    tags: ['Creative', 'Designer', 'Colorful'],
  },
  {
    id: 'res-004',
    name: 'Executive CV',
    description: 'Formal traditional layout for senior professionals',
    serviceId: 6,
    category: 'career',
    style: 'classic',
    thumbnail: '/templates/resume/executive-cv.jpg',
    previewUrl: '/template/res-004/preview',
    isPremium: true,
    tags: ['Executive', 'Formal', 'Senior'],
  },
  {
    id: 'res-005',
    name: 'Fresher Resume Template',
    description: 'Skills-focused layout perfect for entry-level candidates',
    serviceId: 6,
    category: 'career',
    style: 'professional',
    thumbnail: '/templates/resume/fresher.jpg',
    previewUrl: '/template/res-005/preview',
    isPremium: false,
    tags: ['Fresher', 'Entry-level', 'Skills-focused'],
  },
  {
    id: 'res-006',
    name: 'Two-Column Resume',
    description: 'Efficient space usage with modern two-column layout',
    serviceId: 6,
    category: 'career',
    style: 'modern',
    thumbnail: '/templates/resume/two-column.jpg',
    previewUrl: '/template/res-006/preview',
    isPremium: false,
    tags: ['Two-column', 'Efficient', 'Modern'],
  },
  {
    id: 'res-007',
    name: 'Minimalist Black & White',
    description: 'Simple elegant timeless design',
    serviceId: 6,
    category: 'career',
    style: 'minimalist',
    thumbnail: '/templates/resume/minimalist-bw.jpg',
    previewUrl: '/template/res-007/preview',
    isPremium: false,
    tags: ['Minimalist', 'Simple', 'Timeless'],
  },
  {
    id: 'res-008',
    name: 'Technical Resume',
    description: 'Skills bar graphs and certifications for IT professionals',
    serviceId: 6,
    category: 'career',
    style: 'professional',
    thumbnail: '/templates/resume/technical.jpg',
    previewUrl: '/template/res-008/preview',
    isPremium: true,
    tags: ['Technical', 'IT', 'Skills-focused'],
  },
  {
    id: 'res-009',
    name: 'Academic CV',
    description: 'Detailed education and research publication format',
    serviceId: 6,
    category: 'career',
    style: 'classic',
    thumbnail: '/templates/resume/academic-cv.jpg',
    previewUrl: '/template/res-009/preview',
    isPremium: true,
    tags: ['Academic', 'Research', 'Detailed'],
  },
  {
    id: 'res-010',
    name: 'Internship Resume',
    description: 'Projects and learning focused for students',
    serviceId: 6,
    category: 'career',
    style: 'professional',
    thumbnail: '/templates/resume/internship.jpg',
    previewUrl: '/template/res-010/preview',
    isPremium: false,
    tags: ['Internship', 'Student', 'Projects'],
  },
];

// Wedding Invitation Templates
export const weddingInvitationTemplates: Template[] = [
  {
    id: 'wed-001',
    name: 'Royal Palace Wedding Card',
    description: 'Gold foil effect, ornate borders, luxury design',
    serviceId: 2,
    category: 'marriage',
    style: 'premium',
    thumbnail: '/templates/wedding/royal-palace.jpg',
    previewUrl: '/template/wed-001/preview',
    isPremium: true,
    tags: ['Royal', 'Luxury', 'Gold'],
  },
  {
    id: 'wed-002',
    name: 'Floral Garden Invitation',
    description: 'Watercolor flowers, pastel palette, romantic',
    serviceId: 2,
    category: 'marriage',
    style: 'elegant',
    thumbnail: '/templates/wedding/floral-garden.jpg',
    previewUrl: '/template/wed-002/preview',
    isPremium: false,
    tags: ['Floral', 'Romantic', 'Pastel'],
  },
  {
    id: 'wed-003',
    name: 'Modern Geometric Card',
    description: 'Contemporary shapes, bold colors, minimalist',
    serviceId: 2,
    category: 'marriage',
    style: 'modern',
    thumbnail: '/templates/wedding/modern-geometric.jpg',
    previewUrl: '/template/wed-003/preview',
    isPremium: false,
    tags: ['Modern', 'Geometric', 'Bold'],
  },
  {
    id: 'wed-004',
    name: 'Traditional Mandala Design',
    description: 'Intricate patterns, cultural motifs, vibrant',
    serviceId: 2,
    category: 'marriage',
    style: 'traditional',
    thumbnail: '/templates/wedding/mandala.jpg',
    previewUrl: '/template/wed-004/preview',
    isPremium: false,
    tags: ['Traditional', 'Mandala', 'Cultural'],
  },
  {
    id: 'wed-005',
    name: 'Rustic Vintage Invitation',
    description: 'Kraft paper look, handwritten fonts, earthy',
    serviceId: 2,
    category: 'marriage',
    style: 'classic',
    thumbnail: '/templates/wedding/rustic-vintage.jpg',
    previewUrl: '/template/wed-005/preview',
    isPremium: true,
    tags: ['Rustic', 'Vintage', 'Earthy'],
  },
  {
    id: 'wed-006',
    name: 'Elegant Monogram Card',
    description: 'Couple initials, sophisticated, black/white/gold',
    serviceId: 2,
    category: 'marriage',
    style: 'elegant',
    thumbnail: '/templates/wedding/elegant-monogram.jpg',
    previewUrl: '/template/wed-006/preview',
    isPremium: true,
    tags: ['Monogram', 'Elegant', 'Sophisticated'],
  },
  {
    id: 'wed-007',
    name: 'Destination Wedding Theme',
    description: 'Beach/mountain graphics, travel-inspired',
    serviceId: 2,
    category: 'marriage',
    style: 'creative',
    thumbnail: '/templates/wedding/destination.jpg',
    previewUrl: '/template/wed-007/preview',
    isPremium: false,
    tags: ['Destination', 'Travel', 'Beach'],
  },
  {
    id: 'wed-008',
    name: 'Royal Rajasthani Card',
    description: 'Elephant motifs, mirror work inspired, colorful',
    serviceId: 2,
    category: 'marriage',
    style: 'traditional',
    thumbnail: '/templates/wedding/rajasthani.jpg',
    previewUrl: '/template/wed-008/preview',
    isPremium: true,
    tags: ['Rajasthani', 'Royal', 'Colorful'],
  },
  {
    id: 'wed-009',
    name: 'Contemporary Photo Card',
    description: 'Large couple photo, modern typography, clean',
    serviceId: 2,
    category: 'marriage',
    style: 'modern',
    thumbnail: '/templates/wedding/photo-card.jpg',
    previewUrl: '/template/wed-009/preview',
    isPremium: false,
    tags: ['Photo', 'Modern', 'Contemporary'],
  },
  {
    id: 'wed-010',
    name: 'Digital Animated Invitation',
    description: 'Video template, motion graphics, shareable',
    serviceId: 2,
    category: 'marriage',
    style: 'creative',
    thumbnail: '/templates/wedding/animated.jpg',
    previewUrl: '/template/wed-010/preview',
    isPremium: true,
    tags: ['Animated', 'Video', 'Digital'],
  },
];

// Certificate Templates
export const certificateTemplates: Template[] = [
  {
    id: 'cert-001',
    name: 'Achievement Certificate',
    description: 'Border design, seal, formal recognition',
    serviceId: 12,
    category: 'business',
    style: 'professional',
    thumbnail: '/templates/certificate/achievement.jpg',
    previewUrl: '/template/cert-001/preview',
    isPremium: false,
    tags: ['Achievement', 'Formal', 'Professional'],
  },
  {
    id: 'cert-002',
    name: 'Participation Certificate',
    description: 'Event name, date, attendee appreciation',
    serviceId: 12,
    category: 'business',
    style: 'professional',
    thumbnail: '/templates/certificate/participation.jpg',
    previewUrl: '/template/cert-002/preview',
    isPremium: false,
    tags: ['Participation', 'Event', 'Appreciation'],
  },
  {
    id: 'cert-003',
    name: 'Course Completion',
    description: 'Training details, skills acquired, educational',
    serviceId: 12,
    category: 'business',
    style: 'professional',
    thumbnail: '/templates/certificate/course-completion.jpg',
    previewUrl: '/template/cert-003/preview',
    isPremium: false,
    tags: ['Course', 'Training', 'Education'],
  },
  {
    id: 'cert-004',
    name: 'Award Certificate',
    description: 'Trophy graphics, winner recognition, prestigious',
    serviceId: 12,
    category: 'business',
    style: 'premium',
    thumbnail: '/templates/certificate/award.jpg',
    previewUrl: '/template/cert-004/preview',
    isPremium: true,
    tags: ['Award', 'Winner', 'Trophy'],
  },
  {
    id: 'cert-005',
    name: 'Appreciation Certificate',
    description: 'Thank you message, decorative, gratitude',
    serviceId: 12,
    category: 'business',
    style: 'elegant',
    thumbnail: '/templates/certificate/appreciation.jpg',
    previewUrl: '/template/cert-005/preview',
    isPremium: false,
    tags: ['Appreciation', 'Thank you', 'Gratitude'],
  },
  {
    id: 'cert-006',
    name: 'Workshop Certificate',
    description: 'Hours completed, topics covered, professional development',
    serviceId: 12,
    category: 'business',
    style: 'professional',
    thumbnail: '/templates/certificate/workshop.jpg',
    previewUrl: '/template/cert-006/preview',
    isPremium: false,
    tags: ['Workshop', 'Training', 'Professional'],
  },
  {
    id: 'cert-007',
    name: 'Volunteer Recognition',
    description: 'Service hours, impact highlighted, charitable',
    serviceId: 12,
    category: 'business',
    style: 'elegant',
    thumbnail: '/templates/certificate/volunteer.jpg',
    previewUrl: '/template/cert-007/preview',
    isPremium: true,
    tags: ['Volunteer', 'Service', 'Charity'],
  },
  {
    id: 'cert-008',
    name: 'Sports Certificate',
    description: 'Athletic graphics, competition details, winner',
    serviceId: 12,
    category: 'business',
    style: 'creative',
    thumbnail: '/templates/certificate/sports.jpg',
    previewUrl: '/template/cert-008/preview',
    isPremium: false,
    tags: ['Sports', 'Athletic', 'Competition'],
  },
  {
    id: 'cert-009',
    name: 'Academic Excellence',
    description: 'School/university seal, grades, scholarly',
    serviceId: 12,
    category: 'business',
    style: 'classic',
    thumbnail: '/templates/certificate/academic.jpg',
    previewUrl: '/template/cert-009/preview',
    isPremium: true,
    tags: ['Academic', 'Excellence', 'Scholarly'],
  },
  {
    id: 'cert-010',
    name: 'Gift Certificate',
    description: 'Value amount, terms, business branding, voucher',
    serviceId: 12,
    category: 'business',
    style: 'colorful',
    thumbnail: '/templates/certificate/gift.jpg',
    previewUrl: '/template/cert-010/preview',
    isPremium: false,
    tags: ['Gift', 'Voucher', 'Business'],
  },
];

// Business Card Templates
export const businessCardTemplates: Template[] = [
  {
    id: 'bc-001',
    name: 'Minimalist Professional',
    description: 'Name/title/contact, simple, clean',
    serviceId: 13,
    category: 'business',
    style: 'minimalist',
    thumbnail: '/templates/business-card/minimalist.jpg',
    previewUrl: '/template/bc-001/preview',
    isPremium: false,
    tags: ['Minimalist', 'Clean', 'Simple'],
  },
  {
    id: 'bc-002',
    name: 'Creative Colorful',
    description: 'Vibrant colors, unique layout, memorable',
    serviceId: 13,
    category: 'business',
    style: 'creative',
    thumbnail: '/templates/business-card/creative.jpg',
    previewUrl: '/template/bc-002/preview',
    isPremium: false,
    tags: ['Creative', 'Colorful', 'Unique'],
  },
  {
    id: 'bc-003',
    name: 'Corporate Traditional',
    description: 'Formal, company logo, conventional',
    serviceId: 13,
    category: 'business',
    style: 'corporate',
    thumbnail: '/templates/business-card/corporate.jpg',
    previewUrl: '/template/bc-003/preview',
    isPremium: false,
    tags: ['Corporate', 'Traditional', 'Formal'],
  },
  {
    id: 'bc-004',
    name: 'Modern Two-Sided',
    description: 'Front photo/logo, back details, informative',
    serviceId: 13,
    category: 'business',
    style: 'modern',
    thumbnail: '/templates/business-card/two-sided.jpg',
    previewUrl: '/template/bc-004/preview',
    isPremium: true,
    tags: ['Modern', 'Two-sided', 'Informative'],
  },
  {
    id: 'bc-005',
    name: 'QR Code Card',
    description: 'Scannable digital contact, tech-forward, innovative',
    serviceId: 13,
    category: 'business',
    style: 'modern',
    thumbnail: '/templates/business-card/qr-code.jpg',
    previewUrl: '/template/bc-005/preview',
    isPremium: true,
    tags: ['QR Code', 'Tech', 'Digital'],
  },
  {
    id: 'bc-006',
    name: 'Vertical Layout',
    description: 'Portrait orientation, stands out, unique',
    serviceId: 13,
    category: 'business',
    style: 'creative',
    thumbnail: '/templates/business-card/vertical.jpg',
    previewUrl: '/template/bc-006/preview',
    isPremium: false,
    tags: ['Vertical', 'Unique', 'Portrait'],
  },
  {
    id: 'bc-007',
    name: 'Photo Business Card',
    description: 'Professional headshot, personal branding',
    serviceId: 13,
    category: 'business',
    style: 'professional',
    thumbnail: '/templates/business-card/photo.jpg',
    previewUrl: '/template/bc-007/preview',
    isPremium: false,
    tags: ['Photo', 'Personal', 'Professional'],
  },
  {
    id: 'bc-008',
    name: 'Textured Premium',
    description: 'Luxury feel, embossed look, high-end',
    serviceId: 13,
    category: 'business',
    style: 'premium',
    thumbnail: '/templates/business-card/premium.jpg',
    previewUrl: '/template/bc-008/preview',
    isPremium: true,
    tags: ['Premium', 'Luxury', 'Textured'],
  },
  {
    id: 'bc-009',
    name: 'Social Media Focused',
    description: 'Instagram/LinkedIn handles prominent, digital-native',
    serviceId: 13,
    category: 'business',
    style: 'modern',
    thumbnail: '/templates/business-card/social-media.jpg',
    previewUrl: '/template/bc-009/preview',
    isPremium: false,
    tags: ['Social Media', 'Digital', 'Modern'],
  },
  {
    id: 'bc-010',
    name: 'Eco-Friendly Design',
    description: 'Green theme, sustainability messaging, conscious',
    serviceId: 13,
    category: 'business',
    style: 'creative',
    thumbnail: '/templates/business-card/eco.jpg',
    previewUrl: '/template/bc-010/preview',
    isPremium: true,
    tags: ['Eco-friendly', 'Green', 'Sustainable'],
  },
];
