import { Template } from '@/types';

// Marriage Biodata Templates
export const marriageBiodataTemplates: Template[] = [
  {
    id: 'mb-001',
    name: 'Traditional Hindu Biodata',
    description: 'Classic Hindu marriage biodata with religious symbols',
    category: 'Marriage Biodata',
    isPremium: false,
    imageUrl: '/templates/marriage/traditional-hindu.jpg',
    tags: ['Hindu', 'Traditional', 'Religious'],
  },
  {
    id: 'mb-002',
    name: 'Modern Minimalist Biodata',
    description: 'Clean and contemporary design for modern couples',
    category: 'Marriage Biodata',
    isPremium: false,
    imageUrl: '/templates/marriage/modern-minimal.jpg',
    tags: ['Modern', 'Minimalist', 'Simple'],
  },
  {
    id: 'mb-003',
    name: 'Muslim Nikah Biodata',
    description: 'Islamic marriage biodata with Arabic calligraphy',
    category: 'Marriage Biodata',
    isPremium: false,
    imageUrl: '/templates/marriage/muslim-nikah.jpg',
    tags: ['Muslim', 'Islamic', 'Traditional'],
  },
  {
    id: 'mb-004',
    name: 'Christian Marriage Resume',
    description: 'Christian matrimony biodata with cross and blessings',
    category: 'Marriage Biodata',
    isPremium: false,
    imageUrl: '/templates/marriage/christian.jpg',
    tags: ['Christian', 'Church', 'Traditional'],
  },
  {
    id: 'mb-005',
    name: 'South Indian Biodata',
    description: 'Traditional Tamil/Telugu style biodata',
    category: 'Marriage Biodata',
    isPremium: true,
    imageUrl: '/templates/marriage/south-indian.jpg',
    tags: ['South Indian', 'Tamil', 'Traditional'],
  },
  {
    id: 'mb-006',
    name: 'Marwari Biodata',
    description: 'Rajasthani Marwari community biodata format',
    category: 'Marriage Biodata',
    isPremium: true,
    imageUrl: '/templates/marriage/marwari.jpg',
    tags: ['Marwari', 'Rajasthani', 'Traditional'],
  },
  {
    id: 'mb-007',
    name: 'Professional Photo Biodata',
    description: 'Photo-centric design with clean layout',
    category: 'Marriage Biodata',
    isPremium: false,
    imageUrl: '/templates/marriage/photo-biodata.jpg',
    tags: ['Photo', 'Modern', 'Professional'],
  },
  {
    id: 'mb-008',
    name: 'Floral Design Biodata',
    description: 'Elegant floral patterns for a romantic touch',
    category: 'Marriage Biodata',
    isPremium: true,
    imageUrl: '/templates/marriage/floral.jpg',
    tags: ['Floral', 'Elegant', 'Romantic'],
  },
  {
    id: 'mb-009',
    name: 'Royal Palace Biodata',
    description: 'Luxurious design with golden accents',
    category: 'Marriage Biodata',
    isPremium: true,
    imageUrl: '/templates/marriage/royal-palace.jpg',
    tags: ['Royal', 'Luxury', 'Premium'],
  },
  {
    id: 'mb-010',
    name: 'Simple One-Page Biodata',
    description: 'Straightforward single-page format',
    category: 'Marriage Biodata',
    isPremium: false,
    imageUrl: '/templates/marriage/simple-one-page.jpg',
    tags: ['Simple', 'One-page', 'Basic'],
  },
];

// Resume Templates
export const resumeTemplates: Template[] = [
  {
    id: 'res-001',
    name: 'ATS-Friendly Resume',
    description: 'Optimized for Applicant Tracking Systems',
    category: 'Resume/CV',
    isPremium: false,
    imageUrl: '/templates/resume/ats-friendly.jpg',
    tags: ['ATS', 'Professional', 'Clean'],
  },
  {
    id: 'res-002',
    name: 'Modern Professional CV',
    description: 'Contemporary design for experienced professionals',
    category: 'Resume/CV',
    isPremium: false,
    imageUrl: '/templates/resume/modern-professional.jpg',
    tags: ['Modern', 'Professional', 'Clean'],
  },
  {
    id: 'res-003',
    name: 'Creative Designer Resume',
    description: 'Bold and creative for designers and artists',
    category: 'Resume/CV',
    isPremium: true,
    imageUrl: '/templates/resume/creative-designer.jpg',
    tags: ['Creative', 'Designer', 'Colorful'],
  },
  {
    id: 'res-004',
    name: 'Executive CV',
    description: 'Premium template for senior executives',
    category: 'Resume/CV',
    isPremium: true,
    imageUrl: '/templates/resume/executive.jpg',
    tags: ['Executive', 'Senior', 'Premium'],
  },
  {
    id: 'res-005',
    name: 'Fresher Resume Template',
    description: 'Perfect for college graduates and entry-level',
    category: 'Resume/CV',
    isPremium: false,
    imageUrl: '/templates/resume/fresher.jpg',
    tags: ['Fresher', 'Entry-level', 'Student'],
  },
  {
    id: 'res-006',
    name: 'Two-Column Resume',
    description: 'Efficient two-column layout',
    category: 'Resume/CV',
    isPremium: false,
    imageUrl: '/templates/resume/two-column.jpg',
    tags: ['Two-column', 'Modern', 'Efficient'],
  },
  {
    id: 'res-007',
    name: 'Minimalist Black & White',
    description: 'Simple monochrome design',
    category: 'Resume/CV',
    isPremium: false,
    imageUrl: '/templates/resume/minimalist-bw.jpg',
    tags: ['Minimalist', 'Simple', 'Clean'],
  },
  {
    id: 'res-008',
    name: 'Technical Resume',
    description: 'Optimized for IT and tech professionals',
    category: 'Resume/CV',
    isPremium: true,
    imageUrl: '/templates/resume/technical.jpg',
    tags: ['Technical', 'IT', 'Developer'],
  },
  {
    id: 'res-009',
    name: 'Academic CV',
    description: 'Detailed format for academic positions',
    category: 'Resume/CV',
    isPremium: true,
    imageUrl: '/templates/resume/academic.jpg',
    tags: ['Academic', 'Research', 'Professor'],
  },
  {
    id: 'res-010',
    name: 'Internship Resume',
    description: 'Student-focused template for internships',
    category: 'Resume/CV',
    isPremium: false,
    imageUrl: '/templates/resume/internship.jpg',
    tags: ['Internship', 'Student', 'Entry-level'],
  },
];

// Wedding Invitation Templates
export const weddingInvitationTemplates: Template[] = [
  {
    id: 'wi-001',
    name: 'Royal Palace Wedding Card',
    description: 'Luxurious gold foil design with regal motifs',
    category: 'Wedding Invitation',
    isPremium: true,
    imageUrl: '/templates/wedding/royal-palace.jpg',
    tags: ['Royal', 'Luxury', 'Gold', 'Traditional'],
  },
  {
    id: 'wi-002',
    name: 'Floral Garden Invitation',
    description: 'Romantic watercolor flowers and botanical elements',
    category: 'Wedding Invitation',
    isPremium: false,
    imageUrl: '/templates/wedding/floral-garden.jpg',
    tags: ['Floral', 'Romantic', 'Watercolor', 'Garden'],
  },
  {
    id: 'wi-003',
    name: 'Modern Minimalist Card',
    description: 'Clean geometric design with bold typography',
    category: 'Wedding Invitation',
    isPremium: false,
    imageUrl: '/templates/wedding/modern-minimal.jpg',
    tags: ['Modern', 'Minimalist', 'Geometric', 'Contemporary'],
  },
  {
    id: 'wi-004',
    name: 'Traditional Indian Wedding',
    description: 'Vibrant colors with mandala and peacock motifs',
    category: 'Wedding Invitation',
    isPremium: false,
    imageUrl: '/templates/wedding/traditional-indian.jpg',
    tags: ['Indian', 'Traditional', 'Colorful', 'Mandala'],
  },
  {
    id: 'wi-005',
    name: 'Beach Wedding Invitation',
    description: 'Coastal theme with seashells and ocean colors',
    category: 'Wedding Invitation',
    isPremium: true,
    imageUrl: '/templates/wedding/beach.jpg',
    tags: ['Beach', 'Coastal', 'Destination', 'Tropical'],
  },
  {
    id: 'wi-006',
    name: 'Rustic Barn Wedding',
    description: 'Country-style with wood textures and wildflowers',
    category: 'Wedding Invitation',
    isPremium: true,
    imageUrl: '/templates/wedding/rustic-barn.jpg',
    tags: ['Rustic', 'Country', 'Barn', 'Natural'],
  },
  {
    id: 'wi-007',
    name: 'Elegant Monogram Card',
    description: 'Sophisticated monogram design with elegant borders',
    category: 'Wedding Invitation',
    isPremium: false,
    imageUrl: '/templates/wedding/elegant-monogram.jpg',
    tags: ['Elegant', 'Monogram', 'Sophisticated', 'Classic'],
  },
  {
    id: 'wi-008',
    name: 'Vintage Victorian Style',
    description: 'Classic vintage design with ornate details',
    category: 'Wedding Invitation',
    isPremium: true,
    imageUrl: '/templates/wedding/vintage-victorian.jpg',
    tags: ['Vintage', 'Victorian', 'Classic', 'Ornate'],
  },
  {
    id: 'wi-009',
    name: 'Bohemian Chic Invitation',
    description: 'Free-spirited boho design with dreamcatchers',
    category: 'Wedding Invitation',
    isPremium: true,
    imageUrl: '/templates/wedding/bohemian.jpg',
    tags: ['Bohemian', 'Boho', 'Artistic', 'Unique'],
  },
  {
    id: 'wi-010',
    name: 'Simple Elegant White',
    description: 'Timeless white invitation with subtle accents',
    category: 'Wedding Invitation',
    isPremium: false,
    imageUrl: '/templates/wedding/simple-white.jpg',
    tags: ['Simple', 'Elegant', 'White', 'Timeless'],
  },
];

// ID Card Templates
export const idCardTemplates: Template[] = [
  {
    id: 'id-001',
    name: 'Corporate Employee ID',
    description: 'Professional employee ID with photo and barcode',
    category: 'ID Card',
    isPremium: false,
    imageUrl: '/templates/id-card/corporate-employee.jpg',
    tags: ['Employee', 'Corporate', 'Professional', 'Barcode'],
  },
  {
    id: 'id-002',
    name: 'School Student ID Card',
    description: 'Colorful student ID with school branding',
    category: 'ID Card',
    isPremium: false,
    imageUrl: '/templates/id-card/school-student.jpg',
    tags: ['Student', 'School', 'Education', 'Colorful'],
  },
  {
    id: 'id-003',
    name: 'College ID Card',
    description: 'University student ID with department details',
    category: 'ID Card',
    isPremium: false,
    imageUrl: '/templates/id-card/college.jpg',
    tags: ['College', 'University', 'Student', 'Academic'],
  },
  {
    id: 'id-004',
    name: 'Visitor Pass',
    description: 'Temporary visitor ID with date and time',
    category: 'ID Card',
    isPremium: false,
    imageUrl: '/templates/id-card/visitor-pass.jpg',
    tags: ['Visitor', 'Temporary', 'Guest', 'Access'],
  },
  {
    id: 'id-005',
    name: 'Conference Badge',
    description: 'Event participant badge with QR code',
    category: 'ID Card',
    isPremium: true,
    imageUrl: '/templates/id-card/conference-badge.jpg',
    tags: ['Conference', 'Event', 'Badge', 'QR Code'],
  },
  {
    id: 'id-006',
    name: 'Security Access Card',
    description: 'High-security ID with access levels',
    category: 'ID Card',
    isPremium: true,
    imageUrl: '/templates/id-card/security-access.jpg',
    tags: ['Security', 'Access', 'High-security', 'RFID'],
  },
  {
    id: 'id-007',
    name: 'Gym Membership Card',
    description: 'Fitness center membership ID',
    category: 'ID Card',
    isPremium: false,
    imageUrl: '/templates/id-card/gym-membership.jpg',
    tags: ['Gym', 'Fitness', 'Membership', 'Sports'],
  },
  {
    id: 'id-008',
    name: 'Library Card',
    description: 'Library membership with book icon',
    category: 'ID Card',
    isPremium: false,
    imageUrl: '/templates/id-card/library.jpg',
    tags: ['Library', 'Books', 'Membership', 'Education'],
  },
  {
    id: 'id-009',
    name: 'Press/Media ID',
    description: 'Journalist and media professional ID',
    category: 'ID Card',
    isPremium: true,
    imageUrl: '/templates/id-card/press-media.jpg',
    tags: ['Press', 'Media', 'Journalist', 'Professional'],
  },
  {
    id: 'id-010',
    name: 'Volunteer ID Badge',
    description: 'NGO and volunteer organization ID',
    category: 'ID Card',
    isPremium: false,
    imageUrl: '/templates/id-card/volunteer.jpg',
    tags: ['Volunteer', 'NGO', 'Charity', 'Community'],
  },
];

// Certificate Templates
export const certificateTemplates: Template[] = [
  {
    id: 'cert-001',
    name: 'Course Completion Certificate',
    description: 'Professional certificate for course completion',
    category: 'Certificate',
    isPremium: false,
    imageUrl: '/templates/certificate/course-completion.jpg',
    tags: ['Course', 'Completion', 'Training', 'Education'],
  },
  {
    id: 'cert-002',
    name: 'Achievement Award Certificate',
    description: 'Elegant certificate for achievements and awards',
    category: 'Certificate',
    isPremium: false,
    imageUrl: '/templates/certificate/achievement-award.jpg',
    tags: ['Achievement', 'Award', 'Recognition', 'Excellence'],
  },
  {
    id: 'cert-003',
    name: 'Appreciation Certificate',
    description: 'Thank you certificate for contributions',
    category: 'Certificate',
    isPremium: false,
    imageUrl: '/templates/certificate/appreciation.jpg',
    tags: ['Appreciation', 'Thank You', 'Gratitude', 'Recognition'],
  },
  {
    id: 'cert-004',
    name: 'Participation Certificate',
    description: 'Certificate for event or workshop participation',
    category: 'Certificate',
    isPremium: false,
    imageUrl: '/templates/certificate/participation.jpg',
    tags: ['Participation', 'Event', 'Workshop', 'Seminar'],
  },
  {
    id: 'cert-005',
    name: 'Employee of the Month',
    description: 'Recognition certificate for outstanding employees',
    category: 'Certificate',
    isPremium: true,
    imageUrl: '/templates/certificate/employee-month.jpg',
    tags: ['Employee', 'Recognition', 'Award', 'Achievement'],
  },
  {
    id: 'cert-006',
    name: 'Sports Championship Certificate',
    description: 'Winner certificate for sports competitions',
    category: 'Certificate',
    isPremium: true,
    imageUrl: '/templates/certificate/sports-championship.jpg',
    tags: ['Sports', 'Competition', 'Winner', 'Trophy'],
  },
  {
    id: 'cert-007',
    name: 'Academic Excellence Certificate',
    description: 'Certificate for academic achievements',
    category: 'Certificate',
    isPremium: false,
    imageUrl: '/templates/certificate/academic-excellence.jpg',
    tags: ['Academic', 'Excellence', 'Education', 'Student'],
  },
  {
    id: 'cert-008',
    name: 'Internship Completion',
    description: 'Certificate for successful internship completion',
    category: 'Certificate',
    isPremium: false,
    imageUrl: '/templates/certificate/internship.jpg',
    tags: ['Internship', 'Training', 'Completion', 'Professional'],
  },
  {
    id: 'cert-009',
    name: 'Volunteer Service Certificate',
    description: 'Recognition for volunteer contributions',
    category: 'Certificate',
    isPremium: true,
    imageUrl: '/templates/certificate/volunteer-service.jpg',
    tags: ['Volunteer', 'Service', 'Community', 'Appreciation'],
  },
  {
    id: 'cert-010',
    name: 'Gift Certificate',
    description: 'Customizable gift voucher certificate',
    category: 'Certificate',
    isPremium: true,
    imageUrl: '/templates/certificate/gift-certificate.jpg',
    tags: ['Gift', 'Voucher', 'Coupon', 'Reward'],
  },
];

// Business Card Templates
export const businessCardTemplates: Template[] = [
  {
    id: 'bc-001',
    name: 'Minimalist Professional',
    description: 'Clean and simple design for professionals',
    category: 'Business Card',
    isPremium: false,
    imageUrl: '/templates/business-card/minimalist-professional.jpg',
    tags: ['Minimalist', 'Professional', 'Simple', 'Clean'],
  },
  {
    id: 'bc-002',
    name: 'Creative Colorful',
    description: 'Vibrant design for creative professionals',
    category: 'Business Card',
    isPremium: false,
    imageUrl: '/templates/business-card/creative-colorful.jpg',
    tags: ['Creative', 'Colorful', 'Designer', 'Artistic'],
  },
  {
    id: 'bc-003',
    name: 'Corporate Blue',
    description: 'Traditional corporate style in blue',
    category: 'Business Card',
    isPremium: false,
    imageUrl: '/templates/business-card/corporate-blue.jpg',
    tags: ['Corporate', 'Blue', 'Traditional', 'Business'],
  },
  {
    id: 'bc-004',
    name: 'Modern Black & Gold',
    description: 'Luxurious black card with gold accents',
    category: 'Business Card',
    isPremium: true,
    imageUrl: '/templates/business-card/black-gold.jpg',
    tags: ['Modern', 'Luxury', 'Black', 'Gold', 'Premium'],
  },
  {
    id: 'bc-005',
    name: 'Tech Startup Card',
    description: 'Modern design with QR code for tech companies',
    category: 'Business Card',
    isPremium: false,
    imageUrl: '/templates/business-card/tech-startup.jpg',
    tags: ['Tech', 'Startup', 'Modern', 'QR Code'],
  },
  {
    id: 'bc-006',
    name: 'Elegant Vertical Card',
    description: 'Sophisticated vertical orientation design',
    category: 'Business Card',
    isPremium: true,
    imageUrl: '/templates/business-card/elegant-vertical.jpg',
    tags: ['Elegant', 'Vertical', 'Sophisticated', 'Unique'],
  },
  {
    id: 'bc-007',
    name: 'Photo Business Card',
    description: 'Personal branding with professional photo',
    category: 'Business Card',
    isPremium: false,
    imageUrl: '/templates/business-card/photo-card.jpg',
    tags: ['Photo', 'Personal', 'Real Estate', 'Agent'],
  },
  {
    id: 'bc-008',
    name: 'Lawyer/Attorney Card',
    description: 'Professional legal services business card',
    category: 'Business Card',
    isPremium: true,
    imageUrl: '/templates/business-card/lawyer.jpg',
    tags: ['Lawyer', 'Attorney', 'Legal', 'Professional'],
  },
  {
    id: 'bc-009',
    name: 'Restaurant/Cafe Card',
    description: 'Food business card with appetizing design',
    category: 'Business Card',
    isPremium: true,
    imageUrl: '/templates/business-card/restaurant.jpg',
    tags: ['Restaurant', 'Food', 'Cafe', 'Hospitality'],
  },
  {
    id: 'bc-010',
    name: 'Social Media Influencer',
    description: 'Modern card with social handles and QR code',
    category: 'Business Card',
    isPremium: true,
    imageUrl: '/templates/business-card/influencer.jpg',
    tags: ['Influencer', 'Social Media', 'Modern', 'Personal Brand'],
  },
];

// Export all templates
export const allTemplates: Template[] = [
  ...marriageBiodataTemplates,
  ...resumeTemplates,
  ...weddingInvitationTemplates,
  ...idCardTemplates,
  ...certificateTemplates,
  ...businessCardTemplates,
];
