import { Template } from '@/types';

// Marriage Biodata Templates (10)
export const marriageBiodataTemplates: Template[] = [
  {
    id: 'mb-001',
    name: 'Traditional Hindu Biodata',
    description: 'Classic Hindu marriage biodata with Ganesh motif and traditional design',
    category: 'marriage-biodata',
    isPremium: false,
    thumbnail: '/templates/marriage/hindu-traditional.jpg',
    tags: ['hindu', 'traditional', 'ganesh', 'religious'],
  },
  {
    id: 'mb-002',
    name: 'Modern Minimalist Biodata',
    description: 'Clean and simple biodata design for contemporary couples',
    category: 'marriage-biodata',
    isPremium: false,
    thumbnail: '/templates/marriage/modern-minimal.jpg',
    tags: ['modern', 'minimalist', 'simple', 'elegant'],
  },
  {
    id: 'mb-003',
    name: 'Muslim Nikah Biodata',
    description: 'Islamic marriage biodata with Arabic calligraphy',
    category: 'marriage-biodata',
    isPremium: false,
    thumbnail: '/templates/marriage/muslim-nikah.jpg',
    tags: ['muslim', 'islamic', 'nikah', 'arabic'],
  },
  {
    id: 'mb-004',
    name: 'Christian Marriage Resume',
    description: 'Elegant Christian biodata with cross design',
    category: 'marriage-biodata',
    isPremium: false,
    thumbnail: '/templates/marriage/christian.jpg',
    tags: ['christian', 'cross', 'elegant'],
  },
  {
    id: 'mb-005',
    name: 'South Indian Biodata',
    description: 'Traditional South Indian style with temple border',
    category: 'marriage-biodata',
    isPremium: true,
    thumbnail: '/templates/marriage/south-indian.jpg',
    tags: ['south-indian', 'traditional', 'temple', 'premium'],
  },
  {
    id: 'mb-006',
    name: 'Marwari Biodata',
    description: 'Rich Rajasthani design with royal motifs',
    category: 'marriage-biodata',
    isPremium: true,
    thumbnail: '/templates/marriage/marwari.jpg',
    tags: ['marwari', 'rajasthani', 'royal', 'premium'],
  },
  {
    id: 'mb-007',
    name: 'Professional Photo Biodata',
    description: 'Photo-centric modern biodata layout',
    category: 'marriage-biodata',
    isPremium: false,
    thumbnail: '/templates/marriage/photo-centric.jpg',
    tags: ['photo', 'modern', 'professional'],
  },
  {
    id: 'mb-008',
    name: 'Floral Design Biodata',
    description: 'Beautiful floral patterns and pastel colors',
    category: 'marriage-biodata',
    isPremium: true,
    thumbnail: '/templates/marriage/floral.jpg',
    tags: ['floral', 'pastel', 'elegant', 'premium'],
  },
  {
    id: 'mb-009',
    name: 'Royal Palace Biodata',
    description: 'Luxurious design with gold accents',
    category: 'marriage-biodata',
    isPremium: true,
    thumbnail: '/templates/marriage/royal-palace.jpg',
    tags: ['royal', 'luxury', 'gold', 'premium'],
  },
  {
    id: 'mb-010',
    name: 'Simple One-Page Biodata',
    description: 'Straightforward single-page format',
    category: 'marriage-biodata',
    isPremium: false,
    thumbnail: '/templates/marriage/simple-one-page.jpg',
    tags: ['simple', 'one-page', 'basic'],
  },
];

// Resume Templates (10)
export const resumeTemplates: Template[] = [
  {
    id: 'cv-001',
    name: 'ATS-Friendly Resume',
    description: 'Optimized for Applicant Tracking Systems',
    category: 'resume-cv',
    isPremium: false,
    thumbnail: '/templates/resume/ats-friendly.jpg',
    tags: ['ats', 'modern', 'simple', 'professional'],
  },
  {
    id: 'cv-002',
    name: 'Modern Professional CV',
    description: 'Contemporary design with color accents',
    category: 'resume-cv',
    isPremium: false,
    thumbnail: '/templates/resume/modern-professional.jpg',
    tags: ['modern', 'professional', 'colorful'],
  },
  {
    id: 'cv-003',
    name: 'Creative Designer Resume',
    description: 'Bold and creative layout for designers',
    category: 'resume-cv',
    isPremium: true,
    thumbnail: '/templates/resume/creative-designer.jpg',
    tags: ['creative', 'designer', 'bold', 'premium'],
  },
  {
    id: 'cv-004',
    name: 'Executive CV',
    description: 'Senior-level executive resume format',
    category: 'resume-cv',
    isPremium: true,
    thumbnail: '/templates/resume/executive.jpg',
    tags: ['executive', 'senior', 'formal', 'premium'],
  },
  {
    id: 'cv-005',
    name: 'Fresher Resume Template',
    description: 'Perfect for recent graduates',
    category: 'resume-cv',
    isPremium: false,
    thumbnail: '/templates/resume/fresher.jpg',
    tags: ['fresher', 'graduate', 'entry-level'],
  },
  {
    id: 'cv-006',
    name: 'Two-Column Resume',
    description: 'Space-efficient two-column layout',
    category: 'resume-cv',
    isPremium: false,
    thumbnail: '/templates/resume/two-column.jpg',
    tags: ['two-column', 'efficient', 'modern'],
  },
  {
    id: 'cv-007',
    name: 'Minimalist Black & White',
    description: 'Classic monochrome design',
    category: 'resume-cv',
    isPremium: false,
    thumbnail: '/templates/resume/minimalist-bw.jpg',
    tags: ['minimalist', 'black-white', 'classic'],
  },
  {
    id: 'cv-008',
    name: 'Technical Resume',
    description: 'Optimized for IT and tech professionals',
    category: 'resume-cv',
    isPremium: true,
    thumbnail: '/templates/resume/technical.jpg',
    tags: ['technical', 'it', 'developer', 'premium'],
  },
  {
    id: 'cv-009',
    name: 'Academic CV',
    description: 'Detailed format for academic positions',
    category: 'resume-cv',
    isPremium: true,
    thumbnail: '/templates/resume/academic.jpg',
    tags: ['academic', 'research', 'detailed', 'premium'],
  },
  {
    id: 'cv-010',
    name: 'Internship Resume',
    description: 'Tailored for internship applications',
    category: 'resume-cv',
    isPremium: false,
    thumbnail: '/templates/resume/internship.jpg',
    tags: ['internship', 'student', 'entry-level'],
  },
];

// Wedding Invitation Templates (10)
export const weddingInvitationTemplates: Template[] = [
  {
    id: 'wi-001',
    name: 'Royal Palace Invitation',
    description: 'Luxurious design with gold foil effects',
    category: 'wedding-invitation',
    isPremium: true,
    thumbnail: '/templates/wedding/royal-palace.jpg',
    tags: ['royal', 'luxury', 'gold', 'premium'],
  },
  {
    id: 'wi-002',
    name: 'Floral Elegance',
    description: 'Beautiful watercolor floral design',
    category: 'wedding-invitation',
    isPremium: false,
    thumbnail: '/templates/wedding/floral-elegance.jpg',
    tags: ['floral', 'watercolor', 'elegant'],
  },
  {
    id: 'wi-003',
    name: 'Modern Minimalist',
    description: 'Clean and contemporary invitation',
    category: 'wedding-invitation',
    isPremium: false,
    thumbnail: '/templates/wedding/modern-minimal.jpg',
    tags: ['modern', 'minimalist', 'simple'],
  },
  {
    id: 'wi-004',
    name: 'Traditional Hindu Wedding',
    description: 'Classic Hindu design with Ganesh motif',
    category: 'wedding-invitation',
    isPremium: false,
    thumbnail: '/templates/wedding/hindu-traditional.jpg',
    tags: ['hindu', 'traditional', 'ganesh'],
  },
  {
    id: 'wi-005',
    name: 'Rustic Charm',
    description: 'Vintage rustic wedding invitation',
    category: 'wedding-invitation',
    isPremium: true,
    thumbnail: '/templates/wedding/rustic.jpg',
    tags: ['rustic', 'vintage', 'charm', 'premium'],
  },
  {
    id: 'wi-006',
    name: 'Beach Wedding Card',
    description: 'Tropical beach theme invitation',
    category: 'wedding-invitation',
    isPremium: false,
    thumbnail: '/templates/wedding/beach.jpg',
    tags: ['beach', 'tropical', 'destination'],
  },
  {
    id: 'wi-007',
    name: 'Islamic Nikah Invitation',
    description: 'Elegant Islamic wedding card',
    category: 'wedding-invitation',
    isPremium: false,
    thumbnail: '/templates/wedding/islamic-nikah.jpg',
    tags: ['islamic', 'nikah', 'muslim'],
  },
  {
    id: 'wi-008',
    name: 'Geometric Modern',
    description: 'Contemporary geometric patterns',
    category: 'wedding-invitation',
    isPremium: true,
    thumbnail: '/templates/wedding/geometric.jpg',
    tags: ['geometric', 'modern', 'contemporary', 'premium'],
  },
  {
    id: 'wi-009',
    name: 'Vintage Rose Garden',
    description: 'Classic rose design with vintage feel',
    category: 'wedding-invitation',
    isPremium: true,
    thumbnail: '/templates/wedding/vintage-rose.jpg',
    tags: ['vintage', 'rose', 'classic', 'premium'],
  },
  {
    id: 'wi-010',
    name: 'Digital Animated Invite',
    description: 'Video invitation for WhatsApp/Email',
    category: 'wedding-invitation',
    isPremium: true,
    thumbnail: '/templates/wedding/digital-animated.jpg',
    tags: ['digital', 'animated', 'video', 'premium'],
  },
];

// ID Card Templates (10)
export const idCardTemplates: Template[] = [
  {
    id: 'id-001',
    name: 'Corporate Employee ID',
    description: 'Professional employee identification card',
    category: 'id-card',
    isPremium: false,
    thumbnail: '/templates/id/corporate-employee.jpg',
    tags: ['corporate', 'employee', 'professional'],
  },
  {
    id: 'id-002',
    name: 'Student ID Card',
    description: 'School and college student ID',
    category: 'id-card',
    isPremium: false,
    thumbnail: '/templates/id/student.jpg',
    tags: ['student', 'school', 'college'],
  },
  {
    id: 'id-003',
    name: 'Visitor Pass',
    description: 'Temporary visitor identification',
    category: 'id-card',
    isPremium: false,
    thumbnail: '/templates/id/visitor-pass.jpg',
    tags: ['visitor', 'temporary', 'pass'],
  },
  {
    id: 'id-004',
    name: 'Event Badge',
    description: 'Conference and event attendee badge',
    category: 'id-card',
    isPremium: false,
    thumbnail: '/templates/id/event-badge.jpg',
    tags: ['event', 'conference', 'badge'],
  },
  {
    id: 'id-005',
    name: 'Premium Employee ID',
    description: 'Luxury design with holographic effect',
    category: 'id-card',
    isPremium: true,
    thumbnail: '/templates/id/premium-employee.jpg',
    tags: ['premium', 'luxury', 'holographic'],
  },
  {
    id: 'id-006',
    name: 'Government ID Style',
    description: 'Official government-style ID card',
    category: 'id-card',
    isPremium: true,
    thumbnail: '/templates/id/government.jpg',
    tags: ['government', 'official', 'premium'],
  },
  {
    id: 'id-007',
    name: 'Membership Card',
    description: 'Club and gym membership card',
    category: 'id-card',
    isPremium: false,
    thumbnail: '/templates/id/membership.jpg',
    tags: ['membership', 'club', 'gym'],
  },
  {
    id: 'id-008',
    name: 'Security Access Card',
    description: 'High-security access control card',
    category: 'id-card',
    isPremium: true,
    thumbnail: '/templates/id/security-access.jpg',
    tags: ['security', 'access', 'control', 'premium'],
  },
  {
    id: 'id-009',
    name: 'Volunteer ID Badge',
    description: 'NGO and volunteer identification',
    category: 'id-card',
    isPremium: false,
    thumbnail: '/templates/id/volunteer.jpg',
    tags: ['volunteer', 'ngo', 'charity'],
  },
  {
    id: 'id-010',
    name: 'Barcode ID Card',
    description: 'ID with integrated barcode/QR',
    category: 'id-card',
    isPremium: false,
    thumbnail: '/templates/id/barcode.jpg',
    tags: ['barcode', 'qr-code', 'scanning'],
  },
];

// Certificate Templates (10)
export const certificateTemplates: Template[] = [
  {
    id: 'cert-001',
    name: 'Achievement Certificate',
    description: 'Professional achievement recognition',
    category: 'certificate',
    isPremium: false,
    thumbnail: '/templates/certificate/achievement.jpg',
    tags: ['achievement', 'award', 'recognition'],
  },
  {
    id: 'cert-002',
    name: 'Course Completion',
    description: 'Training and course completion certificate',
    category: 'certificate',
    isPremium: false,
    thumbnail: '/templates/certificate/course-completion.jpg',
    tags: ['course', 'training', 'completion'],
  },
  {
    id: 'cert-003',
    name: 'Appreciation Certificate',
    description: 'Thank you and appreciation certificate',
    category: 'certificate',
    isPremium: false,
    thumbnail: '/templates/certificate/appreciation.jpg',
    tags: ['appreciation', 'thank-you', 'gratitude'],
  },
  {
    id: 'cert-004',
    name: 'Participation Certificate',
    description: 'Event and workshop participation',
    category: 'certificate',
    isPremium: false,
    thumbnail: '/templates/certificate/participation.jpg',
    tags: ['participation', 'event', 'workshop'],
  },
  {
    id: 'cert-005',
    name: 'Gold Border Certificate',
    description: 'Elegant gold border design',
    category: 'certificate',
    isPremium: true,
    thumbnail: '/templates/certificate/gold-border.jpg',
    tags: ['gold', 'elegant', 'luxury', 'premium'],
  },
  {
    id: 'cert-006',
    name: 'Modern Minimalist Certificate',
    description: 'Contemporary clean design',
    category: 'certificate',
    isPremium: false,
    thumbnail: '/templates/certificate/modern-minimal.jpg',
    tags: ['modern', 'minimalist', 'clean'],
  },
  {
    id: 'cert-007',
    name: 'Academic Excellence',
    description: 'Academic achievement certificate',
    category: 'certificate',
    isPremium: true,
    thumbnail: '/templates/certificate/academic.jpg',
    tags: ['academic', 'excellence', 'education', 'premium'],
  },
  {
    id: 'cert-008',
    name: 'Sports Certificate',
    description: 'Sports achievement and participation',
    category: 'certificate',
    isPremium: false,
    thumbnail: '/templates/certificate/sports.jpg',
    tags: ['sports', 'athletics', 'competition'],
  },
  {
    id: 'cert-009',
    name: 'Professional Certification',
    description: 'Industry professional certification',
    category: 'certificate',
    isPremium: true,
    thumbnail: '/templates/certificate/professional.jpg',
    tags: ['professional', 'industry', 'certification', 'premium'],
  },
  {
    id: 'cert-010',
    name: 'Volunteer Service',
    description: 'Community service certificate',
    category: 'certificate',
    isPremium: false,
    thumbnail: '/templates/certificate/volunteer.jpg',
    tags: ['volunteer', 'community', 'service'],
  },
];

// Business Card Templates (10)
export const businessCardTemplates: Template[] = [
  {
    id: 'bc-001',
    name: 'Minimalist Black & White',
    description: 'Clean minimalist business card',
    category: 'business-card',
    isPremium: false,
    thumbnail: '/templates/business/minimal-bw.jpg',
    tags: ['minimalist', 'black-white', 'clean'],
  },
  {
    id: 'bc-002',
    name: 'Modern Corporate',
    description: 'Professional corporate design',
    category: 'business-card',
    isPremium: false,
    thumbnail: '/templates/business/modern-corporate.jpg',
    tags: ['modern', 'corporate', 'professional'],
  },
  {
    id: 'bc-003',
    name: 'Creative Designer Card',
    description: 'Bold and creative layout',
    category: 'business-card',
    isPremium: true,
    thumbnail: '/templates/business/creative-designer.jpg',
    tags: ['creative', 'designer', 'bold', 'premium'],
  },
  {
    id: 'bc-004',
    name: 'Elegant Gold Foil',
    description: 'Luxury card with gold accents',
    category: 'business-card',
    isPremium: true,
    thumbnail: '/templates/business/gold-foil.jpg',
    tags: ['elegant', 'gold', 'luxury', 'premium'],
  },
  {
    id: 'bc-005',
    name: 'Photo Business Card',
    description: 'Card with professional headshot',
    category: 'business-card',
    isPremium: false,
    thumbnail: '/templates/business/photo-card.jpg',
    tags: ['photo', 'professional', 'personal'],
  },
  {
    id: 'bc-006',
    name: 'QR Code Card',
    description: 'Modern card with QR code',
    category: 'business-card',
    isPremium: false,
    thumbnail: '/templates/business/qr-code.jpg',
    tags: ['qr-code', 'modern', 'digital'],
  },
  {
    id: 'bc-007',
    name: 'Colorful Gradient',
    description: 'Vibrant gradient design',
    category: 'business-card',
    isPremium: true,
    thumbnail: '/templates/business/gradient.jpg',
    tags: ['colorful', 'gradient', 'vibrant', 'premium'],
  },
  {
    id: 'bc-008',
    name: 'Vertical Card',
    description: 'Unique vertical orientation',
    category: 'business-card',
    isPremium: false,
    thumbnail: '/templates/business/vertical.jpg',
    tags: ['vertical', 'unique', 'different'],
  },
  {
    id: 'bc-009',
    name: 'Double-Sided Design',
    description: 'Utilizes both front and back',
    category: 'business-card',
    isPremium: true,
    thumbnail: '/templates/business/double-sided.jpg',
    tags: ['double-sided', 'comprehensive', 'premium'],
  },
  {
    id: 'bc-010',
    name: 'Die-Cut Shape',
    description: 'Custom shape business card',
    category: 'business-card',
    isPremium: true,
    thumbnail: '/templates/business/die-cut.jpg',
    tags: ['die-cut', 'custom', 'unique', 'premium'],
  },
];

// Export all templates
export const allTemplates: Template[] = [
  ...marriageBiodataTemplates,
  ...resumeTemplates,
  ...weddingInvitationTemplates,
  ...idCardTemplates,
  ...certificateTemplates,
  ...businessCardTemplates,
];
